server:
  port: 10000

spring:
  graphql:
    graphiql:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: fleet
            client-secret: 61uRLIe9LmzxNVXepGQZxw9jxEhwS0J2
            scope: openid
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: ${KEYCLOAK_URL:http://localhost:3000}/auth/realms/c4u

  cloud:
    gateway:
      routes:
        - id: bp_route
          uri: http://localhost:10011
          predicates:
            - Path=/query/businessPartners
          filters:
            - TokenRelay=

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

de:
  c4u:
    gateway:
      businessPartnerUrl: http://localhost:10011
      tenantUrl: http://localhost:10021

logging:
  level:
    org:
      springframework:
        web: debug
        security: debug
        cloud: debug
